#!/usr/bin/env python3
"""
Email Report Generator - Automate repetitive email reporting tasks
Generates formatted reports from data and sends them via email (SMTP)
"""

import smtplib
import csv
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from datetime import datetime, timedelta
import argparse
from typing import List, Dict, Optional


class ReportGenerator:
    """Generate various types of reports"""
    
    @staticmethod
    def generate_summary_report(data: List[Dict], title: str = "Summary Report") -> str:
        """Generate HTML summary report from data"""
        
        html = f"""
        <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 20px;
                }}
                h1 {{
                    color: #2c3e50;
                    border-bottom: 3px solid #3498db;
                    padding-bottom: 10px;
                }}
                h2 {{
                    color: #34495e;
                    margin-top: 30px;
                }}
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                    box-shadow: 0 2px 3px rgba(0,0,0,0.1);
                }}
                th {{
                    background-color: #3498db;
                    color: white;
                    padding: 12px;
                    text-align: left;
                }}
                td {{
                    padding: 10px;
                    border-bottom: 1px solid #ddd;
                }}
                tr:hover {{
                    background-color: #f5f5f5;
                }}
                .metric {{
                    background-color: #ecf0f1;
                    padding: 15px;
                    margin: 10px 0;
                    border-radius: 5px;
                    border-left: 4px solid #3498db;
                }}
                .footer {{
                    margin-top: 30px;
                    padding-top: 20px;
                    border-top: 1px solid #ddd;
                    color: #7f8c8d;
                    font-size: 0.9em;
                }}
            </style>
        </head>
        <body>
            <h1>{title}</h1>
            <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        """
        
        if data:
            # Add metrics
            html += f"""
            <div class="metric">
                <strong>Total Records:</strong> {len(data)}
            </div>
            """
            
            # Add data table
            html += """
            <h2>Data Overview</h2>
            <table>
                <thead>
                    <tr>
            """
            
            # Table headers
            for key in data[0].keys():
                html += f"<th>{key.replace('_', ' ').title()}</th>"
            
            html += """
                    </tr>
                </thead>
                <tbody>
            """
            
            # Table rows
            for row in data:
                html += "<tr>"
                for value in row.values():
                    html += f"<td>{value}</td>"
                html += "</tr>"
            
            html += """
                </tbody>
            </table>
            """
        
        html += """
            <div class="footer">
                <p>This is an automated report generated by Python Email Report Generator</p>
            </div>
        </body>
        </html>
        """
        
        return html
    
    @staticmethod
    def generate_task_report(tasks: List[Dict]) -> str:
        """Generate task status report"""
        
        completed = [t for t in tasks if t.get('status') == 'completed']
        in_progress = [t for t in tasks if t.get('status') == 'in_progress']
        pending = [t for t in tasks if t.get('status') == 'pending']
        
        html = f"""
        <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 20px;
                }}
                h1 {{
                    color: #2c3e50;
                    border-bottom: 3px solid #3498db;
                    padding-bottom: 10px;
                }}
                .stats {{
                    display: flex;
                    justify-content: space-around;
                    margin: 30px 0;
                }}
                .stat-box {{
                    text-align: center;
                    padding: 20px;
                    border-radius: 8px;
                    flex: 1;
                    margin: 0 10px;
                }}
                .completed {{ background-color: #d4edda; border-left: 4px solid #28a745; }}
                .in-progress {{ background-color: #fff3cd; border-left: 4px solid #ffc107; }}
                .pending {{ background-color: #f8d7da; border-left: 4px solid #dc3545; }}
                .stat-number {{
                    font-size: 2.5em;
                    font-weight: bold;
                    margin: 10px 0;
                }}
                .task-list {{
                    margin: 20px 0;
                }}
                .task-item {{
                    padding: 15px;
                    margin: 10px 0;
                    border-radius: 5px;
                    background-color: #f8f9fa;
                    border-left: 4px solid #3498db;
                }}
            </style>
        </head>
        <body>
            <h1>📊 Task Status Report</h1>
            <p><strong>Report Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            
            <div class="stats">
                <div class="stat-box completed">
                    <div>✅ Completed</div>
                    <div class="stat-number">{len(completed)}</div>
                </div>
                <div class="stat-box in-progress">
                    <div>🔄 In Progress</div>
                    <div class="stat-number">{len(in_progress)}</div>
                </div>
                <div class="stat-box pending">
                    <div>⏳ Pending</div>
                    <div class="stat-number">{len(pending)}</div>
                </div>
            </div>
            
            <h2>Task Details</h2>
        """
        
        for task in tasks:
            status_emoji = {
                'completed': '✅',
                'in_progress': '🔄',
                'pending': '⏳'
            }.get(task.get('status', 'pending'), '❓')
            
            html += f"""
            <div class="task-item">
                <strong>{status_emoji} {task.get('name', 'Unnamed Task')}</strong><br>
                <small>Status: {task.get('status', 'Unknown').replace('_', ' ').title()}</small>
                {f"<br><small>Due: {task.get('due_date', 'N/A')}</small>" if task.get('due_date') else ''}
            </div>
            """
        
        html += """
        </body>
        </html>
        """
        
        return html


class EmailSender:
    """Send emails via SMTP"""
    
    def __init__(self, smtp_server: str, smtp_port: int, username: str, password: str):
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.username = username
        self.password = password
    
    def send_email(
        self,
        to_addresses: List[str],
        subject: str,
        html_content: str,
        attachments: Optional[List[str]] = None,
        cc_addresses: Optional[List[str]] = None
    ):
        """Send HTML email with optional attachments"""
        
        msg = MIMEMultipart('alternative')
        msg['From'] = self.username
        msg['To'] = ', '.join(to_addresses)
        msg['Subject'] = subject
        
        if cc_addresses:
            msg['Cc'] = ', '.join(cc_addresses)
        
        # Attach HTML content
        html_part = MIMEText(html_content, 'html')
        msg.attach(html_part)
        
        # Attach files
        if attachments:
            for filepath in attachments:
                path = Path(filepath)
                if path.exists():
                    with open(path, 'rb') as f:
                        part = MIMEBase('application', 'octet-stream')
                        part.set_payload(f.read())
                        encoders.encode_base64(part)
                        part.add_header(
                            'Content-Disposition',
                            f'attachment; filename= {path.name}'
                        )
                        msg.attach(part)
        
        # Send email
        try:
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.username, self.password)
                
                all_recipients = to_addresses + (cc_addresses or [])
                server.send_message(msg, self.username, all_recipients)
                
                print(f"✅ Email sent successfully to {', '.join(to_addresses)}")
        
        except Exception as e:
            print(f"❌ Failed to send email: {e}")


def load_data_from_file(filepath: str) -> List[Dict]:
    """Load data from JSON or CSV file"""
    path = Path(filepath)
    
    if not path.exists():
        print(f"❌ File not found: {filepath}")
        return []
    
    if path.suffix == '.json':
        with open(path, 'r') as f:
            return json.load(f)
    
    elif path.suffix == '.csv':
        with open(path, 'r') as f:
            return list(csv.DictReader(f))
    
    else:
        print(f"⚠️  Unsupported file format: {path.suffix}")
        return []


def main():
    parser = argparse.ArgumentParser(
        description='Generate and send automated email reports',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate report preview (no email)
  python email_reporter.py --data data.json --preview
  
  # Send summary report
  python email_reporter.py --data data.json --type summary \\
    --to recipient@example.com --subject "Weekly Report" \\
    --smtp smtp.gmail.com --port 587 \\
    --username your@gmail.com --password "your_password"
  
  # Send task report with attachment
  python email_reporter.py --data tasks.json --type task \\
    --to manager@company.com --cc team@company.com \\
    --attach report.pdf --subject "Task Status Update" \\
    --smtp smtp.gmail.com --port 587 \\
    --username your@gmail.com --password "your_password"

Note: For Gmail, use an App Password instead of your regular password.
Generate one at: https://myaccount.google.com/apppasswords
        """
    )
    
    parser.add_argument('--data', required=True, help='Data file (JSON or CSV)')
    parser.add_argument('--type', choices=['summary', 'task'], default='summary',
                       help='Report type')
    parser.add_argument('--preview', action='store_true',
                       help='Preview report without sending email')
    
    # Email options
    parser.add_argument('--to', nargs='+', help='Recipient email addresses')
    parser.add_argument('--cc', nargs='+', help='CC email addresses')
    parser.add_argument('--subject', help='Email subject')
    parser.add_argument('--attach', nargs='+', help='File attachments')
    
    # SMTP options
    parser.add_argument('--smtp', help='SMTP server')
    parser.add_argument('--port', type=int, default=587, help='SMTP port')
    parser.add_argument('--username', help='SMTP username')
    parser.add_argument('--password', help='SMTP password')
    
    args = parser.parse_args()
    
    # Load data
    print(f"📂 Loading data from: {args.data}")
    data = load_data_from_file(args.data)
    
    if not data:
        print("❌ No data loaded")
        return
    
    print(f"✅ Loaded {len(data)} records\n")
    
    # Generate report
    print(f"📝 Generating {args.type} report...")
    
    generator = ReportGenerator()
    
    if args.type == 'summary':
        html_content = generator.generate_summary_report(data, "Summary Report")
    elif args.type == 'task':
        html_content = generator.generate_task_report(data)
    
    # Preview mode
    if args.preview:
        preview_file = Path(f"report_preview_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html")
        with open(preview_file, 'w') as f:
            f.write(html_content)
        print(f"\n👀 Preview saved to: {preview_file.absolute()}")
        print("💡 Open this file in a browser to preview the report")
        return
    
    # Send email
    if not all([args.to, args.subject, args.smtp, args.username, args.password]):
        print("❌ Missing required email parameters")
        print("💡 Use --preview to generate report without sending email")
        return
    
    print(f"\n📧 Sending email...")
    
    sender = EmailSender(args.smtp, args.port, args.username, args.password)
    sender.send_email(
        to_addresses=args.to,
        subject=args.subject,
        html_content=html_content,
        attachments=args.attach,
        cc_addresses=args.cc
    )


if __name__ == '__main__':
    main()
